### ISSUE TITLE
请问支持PDF 或者 Word 格式吗？

### ISSUE THREAD

**Issue by my9074** [xiao555/Resume-it#2]
支持PDF 或者 Word 格式吗？ 方便一些网站在线上传 Resume~

**Comment by xiao555** [comment]
可以保存成pdf格式的

**Comment by my9074** [comment]
通过什么方式呢？ReadMe 没有发现

**Comment by xiao555** [comment]
![image](https://user-images.githubusercontent.com/8833639/28265050-7055985a-6b20-11e7-9273-4def66957e5f.png)
呈现在浏览器上的页面，直接打印即可

**Comment by my9074** [comment]
OK 可以了~谢谢
