### ISSUE TITLE
学长，你好，在使用中发现了如下问题

### ISSUE THREAD

**Issue by Joe19970619** [xiao555/Resume-it#3]
1.学长使用的是Mac系统，所以在配置package.json中的npm scripts的时候，build命令只配置了Mac系统的，建议学长添加配置Windows系统下的命令：‘set NODE_ENV=production gulp’，并在README文档中说明

2.学长的npm scripts中的public命令稍有问题，直接运行会报错，其中rimraf dist会将gulp生成的dist文件直接删除，造成的后果就是Cannot use simple-git on a directory that does not exist.即simple-git无法找到dist文件夹，解决方法一，不使用rimraf dist，让使用者每次手动删除dist文件，再用gulp命令生成新的dist文件，解决方法二，使用其他能刷新dist文件的方法或更改npm scrips顺序

3.在线简历在移动端，尤其在手机上禁用了用户缩放，导致浏览效果较差，望学长可以改进

4.最后非常感谢学长制作这个简历生成器，非常好用，帮了我很大的忙，希望学长工作愉快，希望我能早日像学长这么优秀！

**Comment by xiao555** [comment]
@Joe19970619 你好，很高兴看到你的issues。
1. 第一个问题我有时间改一下
2. 第二个问题public命令顺序是先删除再build最后才发布，build完应该有dist目录了吧，你看看是不是build过程出问题了。
3. 第三个问题，因为我这个工具就是生成简历导出，不打算在移动端用，所以没做响应式。但是工具本身给了你很大的自由度，页面模板，css，js都可以自己写，也就是你可以自己写主题。我的默认主题是我用来打印纸质简历用的。
4. 第四个问题，谢谢，加油！
